import {
  faTachometerAlt,
  faUsers,
  faCog,
  faChartBar,
  faShoppingCart,
  faLifeRing,
  faAngleUp,
  faCircle,
  faListCheck,
  faRobot,
  faEnvelope,
  faCalendar,
  faFileInvoiceDollar,
  faHandshake,
  faMagnifyingGlassDollar,
  faUserTie,
  faClipboardList,
  faMessage,
  faCheckDouble,
  faChartPie,
  faBell,
  faShieldHalved,
  faGaugeHigh,
  faFileContract,
  faMoneyBillWave,
  faProjectDiagram,
  faIdCard,
  faComments,
  faCircleCheck,
  faUserGear,
  faHeadset,
} from "@fortawesome/free-solid-svg-icons";

const sidebarConfig = {
  admin: [
    { name: "Dashboard", path: "/dashboard", icon: faTachometerAlt },
    {
      name: "Manage Users",
      path: "/users",
      icon: faUserGear,
      options: [
        { name: "Clients", path: "/clients", icon: faUserTie },
        { name: "Users", path: "/users", icon: faUsers },
      ],
    },
    {
      name: "Subscriptions",
      path: "/subscriptions",
      icon: faFileInvoiceDollar,
    },
    { name: "Chats", path: "/chats", icon: faComments },
    { name: "Billings", path: "/billings", icon: faMoneyBillWave },
    { name: "System Analytics", path: "/systemanalytics", icon: faChartPie },
    { name: "Support Tickets", path: "/supporttickets", icon: faHeadset },
    { name: "Security", path: "/landing", icon: faShieldHalved },
    { name: "Permissions", path: "/permissions", icon: faUserGear },
    { name: "Settings", path: "/", icon: faCog },
    { name: "System Health", path: "/performance", icon: faGaugeHigh },
    { name: "Notification", path: "/chatbox", icon: faBell },
  ],
  client: [
    { name: "Dashboard", path: "/dashboard", icon: faTachometerAlt },
    {
      name: "Checklist",
      path: "/checklist",
      icon: faListCheck,
      options: [
        { name: "Task List", path: "/check-tasklist", icon: faCheckDouble },
        { name: "Add Task", path: "/check-addtask", icon: faCircleCheck },
      ],
    },
    {
      name: "Task Delegation",
      path: "/task-delegation",
      icon: faListCheck,
      options: [
        { name: "Add Task", path: "/delegation-taskadd", icon: faCircleCheck },
        {
          name: "Task List",
          path: "/delegation-tasklist",
          icon: faCheckDouble,
        },
      ],
    },
    { name: "FMS", path: "/pipeline", icon: faProjectDiagram },
    // { name: "FormBuilder", path: "/FormBuilder", icon: faClipboardList },
    // { name: "Automation", path: "/automation", icon: faRobot },
    // {
    //   name: "Opportunities",
    //   path: "/opportunities",
    //   icon: faMagnifyingGlassDollar,
    // },
    {
      name: "Settings",
      path: "/dashboard",
      icon: faUserTie,
      options: [
        { name: "Permissions", path: "/permissions", icon: faUserGear },
        {
          name: "Contact Management",
          path: "/contactmgmt",
          icon: faIdCard,
          options: [
            { name: "Employees", path: "/contactmgmt/contacts", icon: faUsers },
            {
              name: "Companies",
              path: "/contactmgmt/clients",
              icon: faUserTie,
            },
          ],
        },
        // { name: "Leads", path: "/crm/leads", icon: faMagnifyingGlassDollar },
        // { name: "FMS", path: "/pipeline", icon: faProjectDiagram },
      ],
    },
    // { name: "Form", path: "/form", icon: faClipboardList },
    // {
    //   name: "NBD-Sales WA-Bot(UD)",
    //   path: "/chatbotform",
    //   icon: faRobot,
    //   options: [
    //     { name: "ChatbotForm", path: "/chatbotform", icon: faMessage },
    //     { name: "Chats", path: "/chatbox", icon: faComments },
    //   ],
    // },
    // {
    //   name: "Meta Verification",
    //   path: "/metasignup",
    //   icon: faShieldHalved,
    //   options: [
    //     { name: "Client", path: "/metasignup", icon: faUserTie },
    //     { name: "Template", path: "/metatemplate", icon: faClipboardList },
    //     { name: "Message", path: "/metamessage", icon: faMessage },
    //   ],
    // },
    // { name: "HRM", path: "/sites", icon: faUserTie },
    // { name: "Calendar", path: "/calendar", icon: faCalendar },
    // {
    //   name: "Manage User",
    //   icon: faUserGear,
    //   options: [{ name: "Users", path: "/users", icon: faUsers }],
    // },
    // { name: "Email Connect (UD)", path: "/email", icon: faEnvelope },
    // { name: "Support", path: "/ticketraise", icon: faChartPie },
    // { name: "Analytics", path: "/analytics", icon: faChartBar },
  ],
  user: [
    { name: "Dashboard", path: "/dashboard", icon: faTachometerAlt },
    {
      name: "Checklist",
      path: "/checklist",
      icon: faListCheck,
      options: [
        { name: "Task List", path: "/check-tasklist", icon: faCheckDouble },
      ],
    },
    {
      name: "Task Delegation (UD)",
      path: "/task-delegation",
      icon: faListCheck,
      options: [
        {
          name: "Task List",
          path: "/delegation-tasklist",
          icon: faCheckDouble,
        },
      ],
    },
    {
      name: "Opportunities",
      path: "/opportunities",
      icon: faMagnifyingGlassDollar,
    },
    { name: "Attendance", path: "/attendance", icon: faCalendar },
    { name: "Support", path: "/support", icon: faHeadset },
    { name: "Reports", path: "/reports", icon: faChartPie },
    { name: "Calendar", path: "/calendar", icon: faCalendar },
    { name: "Payment", path: "/payment", icon: faShoppingCart },
    { name: "Analytics", path: "/analytics", icon: faChartBar },
  ],
};

export default sidebarConfig;
